[package]
name = "first-uefi-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-graphics = "0.8.1"
libm = "0.2.11"
log = "0.4.27"
uefi = { version = "0.34.1", features = ["alloc", "global_allocator", "logger", "panic_handler"] }
